// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vidswyunnkwmxgzrhrbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZHN3eXVubmt3bXhnenJocmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTQ5MTcsImV4cCI6MjA2NjE3MDkxN30.T4JOF28i8pEMxnMYG07dzVJBR9-sYpFdO6va6F4gDD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);